- name: Setup Pages
  if: github.ref == 'refs/heads/main'
  uses: actions/configure-pages@v5

- name: Upload docs folder
  if: github.ref == 'refs/heads/main'
  uses: actions/upload-pages-artifact@v3
  with:
    path: docs

- name: Deploy to GitHub Pages
  if: github.ref == 'refs/heads/main'
  id: deployment
  uses: actions/deploy-pages@v4
